import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Flowbite } from "flowbite-react";
import { RootProvider } from "@/providers/RootProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Flowbite >
          <RootProvider>
            <main className="flex flex-col gap-8 items-center w-full">
              {children}
            </main>
          </RootProvider>
        </Flowbite>
      </body>
    </html>
  );
}
